### ISSUE TITLE
Different font-lock from zenburn

### ISSUE THREAD

**Issue by sooheon** [ksjogo/labburn-theme#4]
Hey, thanks for this interesting alternative to zenburn. The concept of lab colors is new to me. I like the idea of cleaning up the colors, but there are some fundamental font-lock differences from zenburn, resulting in clojure code, being too monotone.

These zenburn on top, labburn at bottom. The blue is missing.

<img width="688" alt="screen shot 2016-06-08 at 10 55 06 pm" src="https://cloud.githubusercontent.com/assets/302945/15896641/0ff82ad2-2dcc-11e6-9244-ca14e23796e4.png">
<img width="688" alt="screen shot 2016-06-08 at 10 55 02 pm" src="https://cloud.githubusercontent.com/assets/302945/15896642/0ff95d4e-2dcc-11e6-9ac0-93c586328009.png">

**Comment by ksjogo** [comment]
The theme was intended to be used in conjunction with rainbow-identifiers, which would cover that coloring. I could (re)add standard font lock though.
![capture d ecran 2016-06-08 a 16 25 36](https://cloud.githubusercontent.com/assets/699858/15897673/b3cb0f80-2d95-11e6-99fa-4d949677a2a3.png)

**Comment by sooheon** [comment]
Yeah could you add that in? I don't think I'll be using rainbow-identifiers, it's a bit much for me.

**Comment by ksjogo** [comment]
Could you give me the faces (bins rolls) have in your config? They are just no face, when I open a similar file.

**Comment by sooheon** [comment]
Ah that is due to the setting `cider-font-lock-dynamically`, and they simply apply the same `font-lock-function-name-face` and `font-lock-variable-name-face`. If those are defined, they should just work.

**Comment by ksjogo** [comment]
For some reason both were orange. Never saw that due to rainbow-identifiers.

**Comment by evpav** [comment]
There are still some differences in highlighting with the original:
1. Wrong colour for the `font-lock-type-face`: `labburn-orange` vs `zenburn-blue-1`
2. Several cases where highlighting is lost due to bold font elimination: `font-lock-builtin-face`, `font-lock-regexp-grouping-construct`, `font-lock-regexp-grouping-backslash`.
I think in these cases and in general difference in lightness should be used instead of font weight to provide visual distinction, i.e. bolder weight should be expressed with brighter colour.

**Comment by ksjogo** [comment]
The orange vs blue was intentional as I do not like the blue.
I will look into the others, bold was removed for the same reason, different lightness seems to be a possible idea.

**Comment by evpav** [comment]
> The orange vs blue was intentional as I do not like the blue.

But it is the same colour as the one used for `font-lock-variable-name-face`, which renders variables and types indistinguishable.

**Comment by ksjogo** [comment]
I am running rainbow-identifiers all the time, so do not notice some default font-locking, thank you for the continued report. 
Just increased the lightness a bit, you could check it.

**Comment by evpav** [comment]
Actually I might be wrong about font-lock-regexp-grouping-construct, font-lock-regexp-grouping-backslash faces. Can they ever be used in such context where adjacent symbols use similar colours?

**Comment by ksjogo** [comment]
I tried running the blue yesterday but I do not like it, as some other emacs modes are using it for misc stuff and it looks bad next to red/yellow/green stuff. So I will likely put it back to orange. Not optimal though.

**Comment by evpav** [comment]
At least use another shade of orange then, different from the variable-name-face.

**Comment by ksjogo** [comment]
Ok, I left it as blue and will orangize other stuff as required.
